### ISSUE TITLE
Mixed tabs and spaces inside of files

### ISSUE THREAD

**Issue by spscream** [jlouis/enacl#12]
@jlouis, I'm adding some functions to nif currently(for key exchange) and found what your sources have mixed spaces and tabs inside of the erl and c sources.

Which one style do you prefer? I think it would make sense to add .editorconfig file to this library, so contributors could use it?

**Comment by jlouis** [comment]
Spaces only. It is just that when you use an editor which copies from the line before it and there is a tab character somewhere, it gets distributed around.

**Comment by spscream** [comment]
Could you fix it yourself, or should I make a pr for you?

I'm using this config by default in my vim:
" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

**Comment by jlouis** [comment]
I'll do stuff tomorrow, so if you haven't done it by then, I'll just do it
:)
