### ISSUE TITLE
generichash type spec?

### ISSUE THREAD

**Issue by technion** [jlouis/enacl#17]
Hi,

I was debating writing a PR but I'm still not sure if this is just me reading this wrong. The typespec on enacl:generichash/2 is:

    -spec generichash(iodata(), binary()) -> {ok, binary()} | {error, term()}.

The function itself has the definition:

    generichash(HashSize, Message) ->

As far as I can see, the only input that works for HashSize is pos_integer. I've tried a series of variations of iolists and binaries and you can see the results below.

```
2> enacl:generichash(32, <<"tewst">>).
{ok,<<61,208,165,16,24,163,189,182,68,236,61,135,221,169,
      129,62,180,117,146,23,205,60,77,113,172,116,49,...>>}
3> enacl:generichash([32], <<"tewst">>).
** exception error: bad argument
     in function  enacl_nif:crypto_generichash/3
        called as enacl_nif:crypto_generichash(" ",<<"tewst">>,<<>>)
4> enacl:generichash("32", <<"tewst">>).
** exception error: bad argument
     in function  enacl_nif:crypto_generichash/3
        called as enacl_nif:crypto_generichash("32",<<"tewst">>,<<>>)
5> enacl:generichash(<<"32">>, <<"tewst">>).
** exception error: bad argument
     in function  enacl_nif:crypto_generichash/3
        called as enacl_nif:crypto_generichash(<<"32">>,<<"tewst">>,<<>>)
```

There are defines for ?CRYPTO_GENERICHASH_BYTES which do appear to be merely integers. Based on this spec, using a constant "work" but makes dialyzer mad:

 The call enacl:generichash(32, binary()) breaks the contract (iodata(), binary()) -> {'ok',binary()} | {'error',term()}

I suppose the related question would be, is there a way of accessing these constants from an application using the library?

**Comment by jlouis** [comment]
The type specs for those functions are wrong. They have to be corrected.

Indeed, the type is a triple of a positive integer, an iodata() block and a binary(). It definitely needs a PR.

**Comment by technion** [comment]
Thanks, I'll get one made.
