### ISSUE TITLE
Add support for multipart crypto_sign functions

### ISSUE THREAD

**Issue by hengestone** [jlouis/enacl#22]
I.e. crypto_sign_init, crypto_sign_update, and crypto_sign_final, from https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html

I can arrange an upwork job for this if that helps :)

**Comment by jlouis** [comment]
It would be nice to have. A rough sketch of what is needed is in #29 since the API is going to follow the same structure as this one.

**Comment by jlouis** [comment]
This is now on `master`. However, do note that I want to slightly rewrite the internals because I don't like the way the code flows at the moment. Also, there are some reference counts which are being bumped in odd ways in there I don't like.
