### ISSUE TITLE
edoc not working

### ISSUE THREAD

**Issue by romanr321** [jlouis/enacl#25]
Hi, I can't create documentation using rebar3 edoc. Tried on two machines, which have a working vsn of Rebar3 and edoc works on other projects.
===> Verifying dependencies...
===> Compiling enacl
make: Entering directory '/home/rrabinovich/prj/eNaCl/enacl/c_src'
make: '/home/rrabinovich/prj/eNaCl/enacl/c_src/../priv/enacl_nif.so' is up to date.
make: Leaving directory '/home/rrabinovich/prj/eNaCl/enacl/c_src'
===> Running edoc for enacl
edoc: skipping source file '/home/rrabinovich/prj/eNaCl/enacl/src/enacl.erl': {'EXIT',
                                                                         {{badmatch,
                                                                           {atom,
                                                                            287,
                                                                            '?CRYPTO_GENERICHASH_BYTES_MIN'}},
                                                                          [{edoc_specs,
                                                                            d2e,
                                                                            2,
                                                                            [{file,
                                                                              "edoc_specs.erl"},
                                                                             {line,
                                                                              347}]},
                                                                           {edoc_specs,
                                                                            type,
                                                                            2,
                                                                            [{file,
                                                                              "edoc_specs.erl"},
                                                                             {line,
                                                                              67}]},
                                                                           {edoc_extract,
                                                                            '-get_tags/6-lc$^0/1-0-',
                                                                            2,
                                                                            [{file,
                                                                              [...]},
                                                                             {line,...}]},
                                                                           {edoc_extract,
                                                                            get_tags,
                                                                            6,
                                                                            [{file,...},
                                                                             {...}]},
                                                                           {edoc_extract,
                                                                            get_tags,
                                                                            6,
                                                                            [{...}|...]},
                                                                           {edoc_extract,
                                                                            source1,
                                                                            5,
                                                                            [...]},
                                                                           {edoc_doclet,
                                                                            source,
                                                                            9,...},
                                                                           {lists,
                                                                            foldl,...}]}}.
edoc: error in doclet 'edoc_doclet': {'EXIT',error}.
===> Failed to generate documentation for app 'enacl'

**Comment by jlouis** [comment]
Yep, this is wrong. Closed by 8b8ceff4ef3795f4974, though I didn't look into if the text makes sense.

**Comment by mike-french** [comment]
I see this error in a different library. I assume the real bug is that edoc does not correctly expand macros in integer range type assignments, and the workaround is to explicitly replace any macro in the _`from..to`_ values with the integer literal. 

(Then I am not sure why you used 10 instead of the defined min value of 16, but that's another question :)
