### ISSUE TITLE
Expose crypto_aead_xchacha20poly1305_ietf_* 

### ISSUE THREAD

**Issue by starbelly** [jlouis/enacl#26]
This is a feature request to expose crypto_aead_xchacha20poly1305_ietf_*.

**Comment by jlouis** [comment]
Your wish has been granted by a patch from @hanssv 

It is on `master` and I'm gearing up for a release soonish.

**Comment by starbelly** [comment]
Ahh their patch took care of chacha20 and friends support... This is for xchacha... but, now that those changes are merged I will use them as a template for this. PR on the way...
