### ISSUE TITLE
secretstream support?

### ISSUE THREAD

**Issue by joagre** [jlouis/enacl#29]
Hi,
Would it be hard to add support for secret streams?

https://download.libsodium.org/doc/secret-key_cryptography/secretstream.html

Cheers
/Joakim

**Comment by jlouis** [comment]
Update on this one:

I'm working toward a cleaner repository on the C side of things. This significantly simplifies the implementation of this issue. I'm probably going to slipstream it in once the dust settles from the cleanup.

**Comment by jlouis** [comment]
This should now be possible to add. The general implementation follows that of either multi-part signatures or generic hashing.

**Comment by spscream** [comment]
I implemented it in #44

**Comment by jlouis** [comment]
This has now been merged. Is slated for next release, once we have some EQC tests for the new API.
