### ISSUE TITLE
support multipart API for hashes

### ISSUE THREAD

**Issue by benoitc** [jlouis/enacl#4]
Using the multipart API would save us from using dirty nifs and improve the usage of the scheduler. API is described there:

http://doc.libsodium.org/advanced/sha-2_hash_function.html#multi-part-sha-256-example

and similar API is available for other hash functions.

**Comment by jlouis** [comment]
Yes, this should definitely be supported by the `enacl` application. I'd suggest that if anyone starts working on it, they ping this issue so people don't accidentally start working on the same thing.

**Comment by jlouis** [comment]
@benoitc Do you still need this, or can it be closed? Things may have changed since 2 years ago.

**Comment by jlouis** [comment]
Come to think of it, I'll just close it and you can reopen if you still need this.
