### ISSUE TITLE
pwhash_limit typespec is not available

### ISSUE THREAD

**Issue by serokellcao** [jlouis/enacl#59]
[As reported here](https://git.sr.ht/~doma/do-auth/tree/f3f04699/item/lib/do_auth/crypto.ex#L14), valid pwhash_limit atoms aren't enumerated in typespec "exported" by enacl.
Is there a particular reason for that, or PR adding it would be a good contribution?

**Comment by jlouis** [comment]
It's likely an oversight. I think we should have that.

**Comment by jlouis** [comment]
Does https://github.com/jlouis/enacl/commit/20b230d693ba4c0053ab044be5442fdb6e6b61f0 look right to you? I could cut a point-release if it looks ok.

**Comment by serokellcao** [comment]
Thank you!
I didn't review thoroughly, but it looks like it does what I need.

**Comment by jlouis** [comment]
I pushed it out as 1.2.1 now.
